CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PasswordHash BLOB NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    DateOfBirth TEXT,
    Fullname TEXT,
    PhoneNumber TEXT NOT NULL UNIQUE,
    TelegramName TEXT NOT NULL UNIQUE
); 

CREATE TABLE IF NOT EXISTS Sessions (
    SessionID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    AccessToken TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
); 

CREATE TABLE IF NOT EXISTS PasswordResets (
    ResetID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    ResetToken TEXT NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
); 

CREATE TABLE IF NOT EXISTS AccountConfirmations (
    ConfirmationID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    ConfirmationToken TEXT NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Apps (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Secret TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ExternalAuth (
    ExternalAuthID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    Provider TEXT NOT NULL,
    ProviderID TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
